controllers:
  # left arm controller for dual robot
  left_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_left_joint1
      - arm_left_joint2
      - arm_left_joint3
      - arm_left_joint4
      - arm_left_joint5
      - arm_left_joint6
      - arm_left_joint7
    state_publish_rate: 1000
    action_monitor_rate: 1000
    stop_trajectory_duration: 0.5
    hold_trajectory_duration: 0.5
  # right arm controller for dual robot
  right_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_right_joint1
      - arm_right_joint2
      - arm_right_joint3
      - arm_right_joint4
      - arm_right_joint5
      - arm_right_joint6
      - arm_right_joint7
    state_publish_rate: 1000
    action_monitor_rate: 1000
    stop_trajectory_duration: 0.5
    hold_trajectory_duration: 0.5
  # hyy trajectory controller for single robot
  left_hyy_trajectory_controller:
    type: hyy_controller/HYYController
    joints:
      - arm_left_joint1
      - arm_left_joint2
      - arm_left_joint3
      - arm_left_joint4
      - arm_left_joint5
      - arm_left_joint6
      - arm_left_joint7
    robot_index: 0
  right_hyy_trajectory_controller:
    type: hyy_controller/HYYController
    joints:
      - arm_right_joint1
      - arm_right_joint2
      - arm_right_joint3
      - arm_right_joint4
      - arm_right_joint5
      - arm_right_joint6
      - arm_right_joint7
    robot_index: 1
  # joint state controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    # joints:
    #   - arm_left_joint1
    #   - arm_left_joint2
    #   - arm_left_joint3
    #   - arm_left_joint4
    #   - arm_left_joint5
    #   - arm_left_joint6
    #   - arm_left_joint7
    #   - arm_right_joint1
    #   - arm_right_joint2
    #   - arm_right_joint3
    #   - arm_right_joint4
    #   - arm_right_joint5
    #   - arm_right_joint6
    #   - arm_right_joint7
    publish_rate: 1000

