joint_trajectory_controller: 
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
  state_publish_rate: 1000
  action_monitor_rate: 1000
  stop_trajectory_duration: 0.5
  hold_trajectory_duration: 0.5
hyy_trajectory_controller: 
  type: hyy_controller/HYYController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
joint_state_controller: 
  type: joint_state_controller/JointStateController
  publish_rate: 1000

