left_joint_trajectory_controller:
  type: position_contollers/JointTrajectoryController
  joints:
    - arm_left_joint1
    - arm_left_joint2
    - arm_left_joint3
    - arm_left_joint4
    - arm_left_joint5
    - arm_left_joint6
    - arm_left_joint7
right_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_right_joint1
    - arm_right_joint2
    - arm_right_joint3
    - arm_right_joint4
    - arm_right_joint5
    - arm_right_joint6
    - arm_right_joint7
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - arm_left_joint1
    - arm_left_joint2
    - arm_left_joint3
    - arm_left_joint4
    - arm_left_joint5
    - arm_left_joint6
    - arm_left_joint7
    - arm_right_joint1
    - arm_right_joint2
    - arm_right_joint3
    - arm_right_joint4
    - arm_right_joint5
    - arm_right_joint6
    - arm_right_joint7