# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: base
  joint_model_group_pose: left_arm_home_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_left_joint1
    - arm_left_joint2
    - arm_left_joint3
    - arm_left_joint4
    - arm_left_joint5
    - arm_left_joint6
    - arm_left_joint7
    - arm_right_joint1
    - arm_right_joint2
    - arm_right_joint3
    - arm_right_joint4
    - arm_right_joint5
    - arm_right_joint6
    - arm_right_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: controllers/right_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_right_joint1
      - arm_right_joint2
      - arm_right_joint3
      - arm_right_joint4
      - arm_right_joint5
      - arm_right_joint6
      - arm_right_joint7
  - name: controllers/left_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_left_joint1
      - arm_left_joint2
      - arm_left_joint3
      - arm_left_joint4
      - arm_left_joint5
      - arm_left_joint6
      - arm_left_joint7